package br.com.jaraguacnc.utils;

public class Consts {
	
	public static final String APPLICATION_NAME = "Convert_JRGCNC";
	
	public static final int XML_TYPE_LINE = 1;
	public static final int XML_TYPE_CIRCLE = 2;
	public static final int XML_TYPE_ANG = 3;
	
	public static final String DXF_HEADER_COMMENT = "Generated by Convert_JRGCNC";
	
	public static final String DXF_TYPE_LINE = "LINE";
	public static final String DXF_TYPE_CIRCLE = "CIRCLE";
	public static final String DXF_TYPE_ARC = "ARC";
	
	public static final long COLOR_RED = 1;
	public static final long COLOR_GREEN = 3;
	public static final long COLOR_BLUE = 5;
	public static final long COLOR_YELLOW = 2;
	public static final long COLOR_LIGHTBLUE = 4;
	public static final long COLOR_PINK = 6;
		
	public static final String SECTION = "SECTION";
	public static final String ENTITIES = "ENTITIES";
	public static final String LINE = "LINE";
	public static final String ENDSEC = "ENDSEC";
	public static final String EOF = "EOF";

	
}