package br.com.jaraguacnc.utils;

public class Consts {
	
	public static final int XML_TYPE_LINE = 1;
	public static final int XML_TYPE_CIRCLE = 2;
	public static final int XML_TYPE_ANG = 3;

	public static final int VALUE_1 = 1;
	public static final double VALUE_DOUBLE_0 = 0.0;
	
	public static final String DXF_HEADER_COMMENT = "Generated by Convert_JRGCNC";

	public static final String DXF_LTYPE = "LTYPE";
	public static final String DXF_LAYER = "LAYER";
	
	public static final String DXF_LTYPE_CONTINUOUS = "CONTINUOUS";
	public static final String DXF_LTYPE_CONTINUOUS_DESC = "SolidLine";
	
	public static final String DXF_TYPE_LINE = "LINE";
	public static final String DXF_TYPE_CIRCLE = "CIRCLE";
	public static final String DXF_TYPE_ARC = "ARC";
	public static final String DXF_TYPE_POLYLINE = "POLYLINE";
	public static final String DXF_TYPE_VERTEX = "VERTEX";
	public static final String EXTD_DXF_BULGE = "BULGE";
	
	public static final long COLOR_RED = 1;
	public static final long COLOR_GREEN = 3;
	public static final long COLOR_BLUE = 5;
	public static final long COLOR_YELLOW = 2;
	public static final long COLOR_LIGHTBLUE = 4;
	public static final long COLOR_PINK = 6;

	public static final String ENDLN = "\r\n";
		
	public static final String SECTION = "SECTION";
	public static final String TABLES = "TABLES";
	public static final String TABLE = "TABLE";
	public static final String ENDTAB = "ENDTAB";
	public static final String ENTITIES = "ENTITIES";
	public static final String LINE = "LINE";
	public static final String ENDSEC = "ENDSEC";
	public static final String SEQEND = "SEQEND";
	public static final String EOF = "EOF";
	
	public static final String PERFILAGEM = "PERFILAGEM";
	
	public static final int CONTINUITY_START = 1;
	public static final int CONTINUITY_MID = 2;
	public static final int CONTINUITY_END = 3;
	public static final int CONTINUITY_NOT = 0;
	

	
}